name: recipe_app
description: An enhanced Flutter project for cooking recipes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  


  
  # Database dependencies
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # State Management
  provider: ^6.0.5

  # Favorites and Dark Mode persistence
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to a modern version

flutter:
  uses-material-design: true
  assets:
    - assets/images/
